-- The publication plan for the twenty library articles.
--
-- Generated by scripts/import-articles.mjs --schedule-only from the
-- `schedule` array in that file, which is where the plan is decided.
--
-- One article every two days, from 11 September 2026 to 19 October 2026, in
-- the editorial order the library was built in. That order does not change
-- here; only the dates do.
--
-- `published_at` is a date, and the RLS policy on public.articles compares
-- it against the current UTC date, so a row becomes public on its own day
-- without a deploy. Nothing else about an article is touched: not the text,
-- the title, the slug, the excerpt, the SEO fields, the category or the
-- cover.

do $$
declare
  found integer;
begin
  select count(*) into found from public.articles where slug in (
    'website-of-webshop',
    'van-excel-naar-maatwerksoftware',
    'wat-is-een-3d-productconfigurator',
    'welke-bedrijfsprocessen-moet-je-automatiseren',
    'wat-kost-een-website-of-webshop',
    'technische-kwaliteit-website-webapp-beoordelen',
    'maatwerksoftware-of-standaardsoftware',
    'wanneer-is-een-3d-productconfigurator-zinvol',
    'zapier-make-of-maatwerk',
    'website-vernieuwen-optimaliseren-redesign-herbouwen-replatformen',
    'wat-kost-een-webapplicatie',
    'technische-schuld-software',
    'api-koppeling-laten-maken',
    'wat-kost-een-3d-productconfigurator',
    'core-web-vitals-websiteperformance',
    'klantportaal-laten-maken',
    'website-koppelen-aan-crm',
    'technisch-onderhoud-website-webapp-na-livegang',
    'hoe-werkt-een-3d-productconfigurator-technisch',
    'website-code-data-eigendom-vendor-lock-in'
  );
  if found <> 20 then
    raise exception 'expected 20 library articles to reschedule, found %', found;
  end if;
end
$$;

update public.articles as a
set published_at = v.published_at
from (values
  ('website-of-webshop', '2026-09-11'::date),
  ('van-excel-naar-maatwerksoftware', '2026-09-13'::date),
  ('wat-is-een-3d-productconfigurator', '2026-09-15'::date),
  ('welke-bedrijfsprocessen-moet-je-automatiseren', '2026-09-17'::date),
  ('wat-kost-een-website-of-webshop', '2026-09-19'::date),
  ('technische-kwaliteit-website-webapp-beoordelen', '2026-09-21'::date),
  ('maatwerksoftware-of-standaardsoftware', '2026-09-23'::date),
  ('wanneer-is-een-3d-productconfigurator-zinvol', '2026-09-25'::date),
  ('zapier-make-of-maatwerk', '2026-09-27'::date),
  ('website-vernieuwen-optimaliseren-redesign-herbouwen-replatformen', '2026-09-29'::date),
  ('wat-kost-een-webapplicatie', '2026-10-01'::date),
  ('technische-schuld-software', '2026-10-03'::date),
  ('api-koppeling-laten-maken', '2026-10-05'::date),
  ('wat-kost-een-3d-productconfigurator', '2026-10-07'::date),
  ('core-web-vitals-websiteperformance', '2026-10-09'::date),
  ('klantportaal-laten-maken', '2026-10-11'::date),
  ('website-koppelen-aan-crm', '2026-10-13'::date),
  ('technisch-onderhoud-website-webapp-na-livegang', '2026-10-15'::date),
  ('hoe-werkt-een-3d-productconfigurator-technisch', '2026-10-17'::date),
  ('website-code-data-eigendom-vendor-lock-in', '2026-10-19'::date)
) as v(slug, published_at)
where a.slug = v.slug;
